name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  build-and-push:
    runs-on: runner-2

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/thecavaco/my-app:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/thecavaco/my-app:${{ github.sha }}
