# This is a basic workflow to help you get started with Actions

name: SECRETDELE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  show-secret:
    runs-on: [ runner-2 ]
    steps:
      - name: Print masked message
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          echo "The secret is set"
          # Try printing the secret directly (commented out)
          echo "Secret is $MY_SECRET"
          
          # Demonstrate secret masking:
          # If you uncomment the line above, the actual secret will NOT appear in the logs,
          # it will be replaced with *** automatically by GitHub Actions.

