# This is a basic workflow to help you get started with Actions

name: NODEVERSTION

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  example_matrix:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]
        version: [14, 16, 18]
        
        exclude:
            - os: macos-latest
            version: 12
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}